# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CPSC572-Artist-Network',
                'doc_host': 'https://nathanaelhuh.github.io',
                'git_url': 'https://github.com/nathanaelhuh/CPSC572-Artist-Network',
                'lib_path': 'CPSC572_Artist_Network'},
  'syms': {'CPSC572_Artist_Network.core': {'CPSC572_Artist_Network.core.foo': ('core.html#foo', 'CPSC572_Artist_Network/core.py')}}}
